---
catalogue:
  title: 'Catalogue'
  type: 'catalogue'
  allowed:
    values:
      - value: 'SATELLITE'
        title: 'Satellite'
        description: 'Satellite products'
      - value: 'REF_DATA'
        title: 'Reference'
        description: 'User-uploaded reference and in situ data'
      - value: 'FSTEP_PRODUCTS'
        title: 'FS-TEP Products'
        description: 'All pre-processed data'
      - value: 'CLMS_DATA'
        title: 'Copernicus Land Monitoring Service'
        description: 'Collections and products of the CLMS'
collection:
  title: 'Collection'
  type: 'dynamic'
  allowed: 
    values: ''
  onlyIf:
    'catalogue':
      - 'FSTEP_PRODUCTS'

refDataCollection:
  title: 'Collection'
  type: 'dynamic'
  allowed: 
    values: ''
  onlyIf:
    'catalogue':
      - 'REF_DATA'  
      
clmscollection:
  title: 'Collection'
  type: 'dynamic'
  allowed: 
    values: ''
  onlyIf:
    'catalogue':
      - 'CLMS_DATA'

owner:
  title: 'Owner'
  type: 'text'
  onlyIf:
    'catalogue':
      - 'REF_DATA'
      - 'FSTEP_PRODUCTS'

mission:
  title: 'Collection'
  type: 'select'
  defaultValue: 'sentinel2'
  allowed:
    values:
      - value: 'sentinel1'
        title: 'Sentinel-1'
      - value: 'sentinel2'
        title: 'Sentinel-2'
      - value: 'sentinel3'
        title: 'Sentinel-3'
      - value: 'sentinel5p'
        title: 'Sentinel-5P'
      - value: 'landsat'
        title: 'Landsat'
      - value: 'envisat'
        title: 'Envisat MERIS L1B'
  onlyIf:
    'catalogue':
      - 'SATELLITE'

s2ProcessingLevel:
  title: 'Processing level'
  type: 'select'
  defaultValue: 'L1C'
  allowed:
    values:
#      - value: ''   L2 products not available for download in creodias
#        title: ''
      - value: 'L1C'
        title: 'L1C'
#      - value: 'L2A' L2 products not available for download in creodias
#        title: 'L2A'
  onlyIf:
    'mission':
      - 'sentinel2'

productDate:
  title: 'Product date'
  type: 'daterange'
  description: 'UTC'
  defaultValue:
    - '-3'
    - '0'
  optional: 'true'
    
jobDate:
  title: 'Job date'
  type: 'daterange'
  description: 'UTC'
  defaultValue:
    - '-3'
    - '0'
  onlyIf:
    'catalogue':
      - 'FSTEP_PRODUCTS'
  optional: 'true'
      
publicationDate:
  title: 'Publication date'
  type: 'daterange'
  description: 'UTC'
  defaultValue:
    - '-3'
    - '0'
  onlyIf:
    'catalogue':
      - 'REF_DATA'      
  optional: 'true'    

aoi:
  title: 'AOI'
  type: 'polygon'
  description: 'WKT polygon'

identifier:
  title: 'Identifier'
  type: 'text'
  description: 'Product identifier string'

platform:
  title: 'Platform'
  type: 'select'
  defaultValue: 'Landsat-8'
  allowed:
    values:
      - value: 'Landsat-5'
        title: 'Landsat-5'
        onlyIf:
          'mission':
            - 'landsat'
      - value: 'Landsat-7'
        title: 'Landsat-7'
        onlyIf:
          'mission':
            - 'landsat'
      - value: 'Landsat-8'
        title: 'Landsat-8'
        onlyIf:
          'mission':
            - 'landsat'
  onlyIf:
    'mission':
      - 'landsat'

maxCloudCover:
  title: 'Cloud Coverage'
  type: 'int'
  description: 'Maximum (%)'
  defaultValue: 10
  allowed:
    min: 0
    max: 100
  onlyIf:
    'mission':
      - 'sentinel2'
      - 'landsat'

s1ProductType:
  title: 'Product type'
  type: 'select'
  defaultValue: 'GRD'
  allowed:
    values:
      - value: 'GRD'
        title: 'GRD'
      - value: 'OCN'
        title: 'OCN'
      - value: 'SLC'
        title: 'SLC'
      - value: 'RAW'
        title: 'RAW'
  onlyIf:
    'mission':
      - 'sentinel1'
      
s5pProductType:
  title: 'Product type'
  type: 'select'
  defaultValue: 'GRD'
  allowed:
    values:
      - value: 'L1B_IR_SIR'
        title: 'L1B_IR_SIR'
      - value: 'L1B_IR_UVN'
        title: 'L1B_IR_UVN'
      - value: 'L1B_RA_BD1'
        title: 'L1B_RA_BD1'
      - value: 'L1B_RA_BD2'
        title: 'L1B_RA_BD2'
      - value: 'L1B_RA_BD3'
        title: 'L1B_RA_BD3'
      - value: 'L1B_RA_BD4'
        title: 'L1B_RA_BD4'
      - value: 'L1B_RA_BD5'
        title: 'L1B_RA_BD5'
      - value: 'L1B_RA_BD6'
        title: 'L1B_RA_BD6'                
      - value: 'L1B_RA_BD7'
        title: 'L1B_RA_BD7'
      - value: 'L1B_RA_BD8'
        title: 'L1B_RA_BD8'
      - value: 'L2__AER_AI'
        title: 'L2__AER_AI'
      - value: 'L2__CLOUD_'
        title: 'L2__CLOUD_'
      - value: 'L2__CO____'
        title: 'L2__CO____'
      - value: 'L2__HCHO__'
        title: 'L2__HCHO__'
      - value: 'L2__NO2___'
        title: 'L2__NO2___'
      - value: 'L2__NP_BD3'
        title: 'L2__NP_BD3'
      - value: 'L2__NP_BD6'
        title: 'L2__NP_BD6'
      - value: 'L2__O3____'
        title: 'L2__O3____'        
      - value: 'L2__SO2___'
        title: 'L2__SO2___'                
  onlyIf:
    'mission':
      - 'sentinel5p'

s5pProcessingLevel:
  title: 'Processing Level'
  type: 'select'
  defaultValue: '1B'
  allowed:
    values:
      - value: ''
        title: ''    
      - value: '1B'
        title: 'L1B'
      - value: '2'
        title: 'L2'               
  onlyIf:
    'mission':
      - 'sentinel5p'
      
s1ProcessingLevel:
  title: 'Processing Level'
  type: 'select'
  defaultValue: '1'
  allowed:
    values:
      - value: ''
        title: ''    
      - value: '1'
        title: 'L1'
      - value: '2'
        title: 'L2'               
  onlyIf:
    'mission':
      - 'sentinel1'
      
s3ProcessingLevel:
  title: 'Processing Level'
  type: 'select'
  defaultValue: '1'
  allowed:
    values:
      - value: ''
        title: ''    
      - value: '1'
        title: 'L1'
      - value: '2'
        title: 'L2'               
  onlyIf:
    'mission':
      - 'sentinel3'

orbitDirection:
  title: 'Orbit direction'
  type: 'select'
  defaultValue: ''
  allowed:
    values:
      - value: 'ascending'
        title: 'ASCENDING'
      - value: 'descending'
        title: 'DESCENDING'
      - value: ''
        title: ''
  onlyIf:
    'mission':
      - 'sentinel1'
      - 'sentinel3'
      
s3Instrument:
  title: 'Instrument'
  type: 'select'
  defaultValue: ''
  allowed:
    values:
      - value: ''
        title: ''
      - value: 'SLSTR'
        title: 'SLSTR'
      - value: 'OLCI'
        title: 'OLCI'
      - value: 'SRAL'
        title: 'SRAL'
  onlyIf:
    'mission':
      - 'sentinel3' 
