---
catalogue:
  title: 'Catalogue'
  type: 'catalogue'
  allowed:
    values:
      - value: 'SATELLITE'
        title: 'Satellite'
        description: 'Satellite products'
      - value: 'REF_DATA'
        title: 'Reference'
        description: 'User-uploaded reference and in situ data'
      - value: 'FSTEP_PRODUCTS'
        title: 'FS-TEP Products'
        description: 'All pre-processed data'
        
collection:
  title: 'Collection'
  type: 'dynamic'
  allowed: 
    values: ''
  onlyIf:
    'catalogue':
      - 'FSTEP_PRODUCTS'

owner:
  title: 'Owner'
  type: 'text'
  onlyIf:
    'catalogue':
      - 'REF_DATA'
      - 'FSTEP_PRODUCTS'

mission:
  title: 'Mission'
  type: 'select'
  defaultValue: 'sentinel2'
  allowed:
    values:
      - value: 'sentinel1'
        title: 'Sentinel-1'
      - value: 'sentinel2'
        title: 'Sentinel-2'
      - value: 'sentinel3'
        title: 'Sentinel-3'
      - value: 'landsat'
        title: 'Landsat'
      - value: 'envisat'
        title: 'Envisat'
  onlyIf:
    'catalogue':
      - 'SATELLITE'

s2ProcessingLevel:
  title: 'Processing level'
  type: 'select'
  defaultValue: ''
  allowed:
    values:
      - value: ''
        title: ''
      - value: '1C'
        title: '1C'
      - value: 'L1C'
        title: 'L1C'
      - value: 'L2A'
        title: 'L2A'
  onlyIf:
    'mission':
      - 'sentinel2'

productDate:
  title: 'Product date'
  type: 'daterange'
  description: 'UTC'
  defaultValue:
    - '-3'
    - '0'
  optional: 'true'
    
jobDate:
  title: 'Job date'
  type: 'daterange'
  description: 'UTC'
  defaultValue:
    - '-3'
    - '0'
  onlyIf:
    'catalogue':
      - 'FSTEP_PRODUCTS'
  optional: 'true'
      
publicationDate:
  title: 'Publication date'
  type: 'daterange'
  description: 'UTC'
  defaultValue:
    - '-3'
    - '0'
  onlyIf:
    'catalogue':
      - 'REF_DATA'      
  optional: 'true'    

aoi:
  title: 'AOI'
  type: 'polygon'
  description: 'WKT polygon'

identifier:
  title: 'Identifier'
  type: 'text'
  description: 'Product identifier string'

platform:
  title: 'Platform'
  type: 'select'
  allowed:
    values:
      - value: 'Landsat-5'
        title: 'Landsat-5'
        onlyIf:
          'mission':
            - 'landsat'
      - value: 'Landsat-7'
        title: 'Landsat-7'
        onlyIf:
          'mission':
            - 'landsat'
      - value: 'Landsat-8'
        title: 'Landsat-8'
        onlyIf:
          'mission':
            - 'landsat'
  onlyIf:
    'mission':
      - 'landsat'

maxCloudCover:
  title: 'Cloud Coverage'
  type: 'int'
  description: 'Maximum (%)'
  defaultValue: 10
  allowed:
    min: 0
    max: 100
  onlyIf:
    'mission':
      - 'sentinel2'
      - 'landsat'

s1ProductType:
  title: 'Product type'
  type: 'select'
  defaultValue: 'GRD'
  allowed:
    values:
      - value: 'GRD'
        title: 'GRD'
      - value: 'OCN'
        title: 'OCN'
      - value: 'SLC'
        title: 'SLC'
      - value: 'RAW'
        title: 'RAW'
  onlyIf:
    'mission':
      - 'sentinel1'

orbitDirection:
  title: 'Orbit direction'
  type: 'select'
  defaultValue: 'ASCENDING'
  allowed:
    values:
      - value: 'ascending'
        title: 'Ascending'
      - value: 'descending'
        title: 'Descending'
  onlyIf:
    'mission':
      - 'sentinel1'
